const fs = require('fs');
let c = fs.readFileSync('briefing.html', 'utf8');

const css = [
'',
'        /* PAGE CARDS */',
'        .briefing-page-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:.6rem;margin-top:.5rem}',
'        .briefing-page-card{position:relative;display:flex;flex-direction:column;align-items:center;gap:.35rem;padding:.85rem .45rem .7rem;border-radius:12px;border:1.5px solid rgba(0,0,0,.06);background:#fff;cursor:pointer;transition:all .35s var(--ease);text-align:center;overflow:hidden;user-select:none}',
'        .briefing-page-card::after{content:"";position:absolute;inset:0;border-radius:11px;opacity:0;transition:opacity .3s;background:radial-gradient(circle at 50% 20%,rgba(242,29,100,.05),transparent 70%)}',
'        .briefing-page-card:hover{border-color:rgba(242,29,100,.2);box-shadow:0 4px 16px rgba(242,29,100,.06);transform:translateY(-2px)}',
'        .briefing-page-card:hover::after{opacity:1}',
'        .briefing-page-card:hover .briefing-page-wireframe{border-color:rgba(242,29,100,.2)}',
'        .briefing-page-card:hover .briefing-page-wire div{background:rgba(242,29,100,.12)}',
'        .briefing-page-card.selected{border-color:var(--accent);background:rgba(242,29,100,.03);box-shadow:0 4px 20px rgba(242,29,100,.1);transform:translateY(-2px)}',
'        .briefing-page-card.selected::after{opacity:1}',
'        .briefing-page-card.selected::before{content:"";position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--accent),#ff6b9d)}',
'        .briefing-page-card.selected .briefing-page-title{color:var(--accent)}',
'        .briefing-page-card.selected .briefing-page-icon{background:var(--accent);color:#fff;box-shadow:0 0 14px rgba(242,29,100,.25)}',
'        .briefing-page-card.selected .briefing-page-wire div{background:rgba(242,29,100,.2)}',
'        .briefing-page-card.selected .briefing-page-wire{border-color:rgba(242,29,100,.15)}',
'        .briefing-page-check{position:absolute;top:6px;right:6px;width:16px;height:16px;border-radius:50%;background:var(--accent);color:#fff;display:flex;align-items:center;justify-content:center;opacity:0;transform:scale(.5);transition:all .3s var(--ease);z-index:2}',
'        .briefing-page-card.selected .briefing-page-check{opacity:1;transform:scale(1)}',
'        .briefing-page-check svg{width:9px;height:9px}',
'        .briefing-page-icon{width:32px;height:32px;border-radius:9px;background:var(--accent-soft);border:1px solid var(--accent-border);display:flex;align-items:center;justify-content:center;color:var(--accent);transition:all .35s var(--ease);flex-shrink:0}',
'        .briefing-page-icon svg{width:15px;height:15px}',
'        .briefing-page-title{font-size:.68rem;font-weight:600;color:var(--g1);line-height:1.3;transition:color .3s;position:relative;z-index:1}',
'        .briefing-page-wire{width:100%;max-width:56px;height:28px;border-radius:4px;border:1px solid rgba(0,0,0,.08);display:flex;flex-direction:column;gap:2px;padding:3px;transition:border-color .3s;position:relative;z-index:1}',
'        .briefing-page-wire div{border-radius:1px;background:rgba(0,0,0,.06);transition:background .3s}',
'        .briefing-page-wire div:first-child{height:8px;border-radius:2px}',
'        .briefing-page-wire div:nth-child(2){height:5px;width:70%}',
'        .briefing-page-wire div:nth-child(3){height:3px;width:50%}',
'        .briefing-page-complexity{font-size:.45rem;color:var(--g2);text-transform:uppercase;letter-spacing:.3px;padding:1px 5px;border-radius:3px;background:rgba(0,0,0,.03);position:relative;z-index:1;line-height:1.4}',
'        .briefing-page-complexity.simple{color:#00b894}',
'        .briefing-page-complexity.medium{color:#f39c12}',
'        .briefing-page-complexity.hard{color:#e17055}',
'        .briefing-page-desc{font-size:.48rem;color:var(--g2);line-height:1.25;position:relative;z-index:1;max-height:0;opacity:0;overflow:hidden;transition:all .35s var(--ease);text-align:center}',
'        .briefing-page-card.selected .briefing-page-desc{max-height:40px;opacity:1;margin-top:.05rem}',
'',
'        /* FUNCTION CARDS */',
'        .briefing-func-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin-top:.5rem}',
'        .briefing-func-card{position:relative;display:flex;flex-direction:column;align-items:center;gap:.3rem;padding:.75rem .4rem .6rem;border-radius:12px;border:1.5px solid rgba(0,0,0,.06);background:#fff;cursor:pointer;transition:all .35s var(--ease);text-align:center;overflow:hidden;user-select:none}',
'        .briefing-func-card::after{content:"";position:absolute;inset:0;border-radius:11px;opacity:0;transition:opacity .3s;background:radial-gradient(circle at 50% 20%,rgba(242,29,100,.05),transparent 70%)}',
'        .briefing-func-card:hover{border-color:rgba(242,29,100,.2);box-shadow:0 4px 16px rgba(242,29,100,.06);transform:translateY(-2px)}',
'        .briefing-func-card:hover::after{opacity:1}',
'        .briefing-func-card.selected{border-color:var(--accent);background:rgba(242,29,100,.03);box-shadow:0 4px 20px rgba(242,29,100,.1);transform:translateY(-2px)}',
'        .briefing-func-card.selected::after{opacity:1}',
'        .briefing-func-card.selected::before{content:"";position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--accent),#ff6b9d)}',
'        .briefing-func-card.selected .briefing-func-title{color:var(--accent)}',
'        .briefing-func-card.selected .briefing-func-icon{background:var(--accent);color:#fff;box-shadow:0 0 14px rgba(242,29,100,.25)}',
'        .briefing-func-check{position:absolute;top:6px;right:6px;width:16px;height:16px;border-radius:50%;background:var(--accent);color:#fff;display:flex;align-items:center;justify-content:center;opacity:0;transform:scale(.5);transition:all .3s var(--ease);z-index:2}',
'        .briefing-func-card.selected .briefing-func-check{opacity:1;transform:scale(1)}',
'        .briefing-func-check svg{width:9px;height:9px}',
'        .briefing-func-icon{width:30px;height:30px;border-radius:8px;background:var(--accent-soft);border:1px solid var(--accent-border);display:flex;align-items:center;justify-content:center;color:var(--accent);transition:all .35s var(--ease);flex-shrink:0}',
'        .briefing-func-icon svg{width:14px;height:14px}',
'        .briefing-func-title{font-size:.62rem;font-weight:600;color:var(--g1);line-height:1.25;transition:color .3s;position:relative;z-index:1}',
'        .briefing-func-badge{font-size:.42rem;font-weight:600;padding:1px 5px;border-radius:3px;text-transform:uppercase;letter-spacing:.3px;position:relative;z-index:1}',
'        .briefing-func-badge.free{background:rgba(0,184,148,.08);color:#00b894;border:1px solid rgba(0,184,148,.15)}',
'        .briefing-func-badge.premium{background:rgba(242,29,100,.06);color:var(--accent);border:1px solid rgba(242,29,100,.12)}',
'        .briefing-func-desc{font-size:.46rem;color:var(--g2);line-height:1.2;position:relative;z-index:1;max-height:0;opacity:0;overflow:hidden;transition:all .35s var(--ease);text-align:center}',
'        .briefing-func-card.selected .briefing-func-desc{max-height:35px;opacity:1;margin-top:.05rem}',
'',
'        /* PACKAGE BUTTONS */',
'        .briefing-packages{display:flex;gap:.5rem;margin-top:.6rem;flex-wrap:wrap}',
'        .briefing-pkg{display:flex;align-items:center;gap:.4rem;padding:.55rem .8rem;border-radius:10px;border:1.5px solid rgba(0,0,0,.06);background:#fff;cursor:pointer;transition:all .3s var(--ease);user-select:none}',
'        .briefing-pkg:hover{border-color:rgba(242,29,100,.25);box-shadow:0 2px 12px rgba(242,29,100,.06);transform:translateY(-1px)}',
'        .briefing-pkg.active{border-color:var(--accent);background:rgba(242,29,100,.04);box-shadow:0 2px 16px rgba(242,29,100,.08)}',
'        .briefing-pkg-icon{font-size:.9rem;line-height:1}',
'        .briefing-pkg-text{display:flex;flex-direction:column;align-items:flex-start;gap:1px}',
'        .briefing-pkg-name{font-size:.65rem;font-weight:600;color:var(--g1);transition:color .3s}',
'        .briefing-pkg.active .briefing-pkg-name{color:var(--accent)}',
'        .briefing-pkg-detail{font-size:.48rem;color:var(--g2);line-height:1.2}',
'        .briefing-pkg-check{width:14px;height:14px;border-radius:50%;border:1.5px solid rgba(0,0,0,.12);display:flex;align-items:center;justify-content:center;transition:all .3s var(--ease);flex-shrink:0}',
'        .briefing-pkg.active .briefing-pkg-check{border-color:var(--accent);background:var(--accent);color:#fff}',
'        .briefing-pkg-check svg{width:8px;height:8px;opacity:0;transition:opacity .2s}',
'        .briefing-pkg.active .briefing-pkg-check svg{opacity:1}',
'',
'        /* COMPLEXITY BAR */',
'        .briefing-complexity{margin-top:.7rem;display:flex;flex-direction:column;gap:.35rem}',
'        .briefing-complexity-header{display:flex;justify-content:space-between;align-items:center}',
'        .briefing-complexity-label{font-size:.6rem;font-weight:600;color:var(--g1);text-transform:uppercase;letter-spacing:.3px}',
'        .briefing-complexity-level{font-size:.58rem;font-weight:600;padding:1px 6px;border-radius:4px;transition:all .3s var(--ease)}',
'        .briefing-complexity-level.simple{background:rgba(0,184,148,.08);color:#00b894}',
'        .briefing-complexity-level.medium{background:rgba(243,156,18,.08);color:#f39c12}',
'        .briefing-complexity-level.hard{background:rgba(225,112,85,.08);color:#e17055}',
'        .briefing-complexity-level.premium{background:rgba(242,29,100,.08);color:var(--accent)}',
'        .briefing-complexity-track{width:100%;height:5px;border-radius:3px;background:rgba(0,0,0,.04);overflow:hidden}',
'        .briefing-complexity-fill{height:100%;border-radius:3px;transition:width .6s var(--ease),background .6s var(--ease);width:0}',
'',
''

].join('\n');

const marker = 'briefing-upload{border:2px dashed';
const idx = c.indexOf(marker);
if (idx === -1) { console.log('ERROR: marker not found'); process.exit(1); }
const lineStart = c.lastIndexOf('/*', idx);
c = c.slice(0, lineStart) + css + c.slice(lineStart);
fs.writeFileSync('briefing.html', c, 'utf8');
console.log('CSS inserted at', lineStart);
